services:
  server:
    container_name: 'server'
    build: ./server
    ports:
      - 8000:8000
    command: >
      sh -c "sleep 5 && 
             alembic upgrade head && 
             uvicorn app.main:app --host 0.0.0.0 --port 8000"

    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/health"]
      interval: 10s 
      timeout: 5s   
      retries: 3    
      start_period: 15s
    
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server:/app
    restart: always
    
       
  check_updates:
    container_name: 'checkUpdates'
    build: ./checkUpdates
    depends_on:
      server:
        condition: service_healthy
    volumes:
      - ./checkUpdates:/src/app
    restart: always

  tgbot:
    container_name: 'TGBot'
    build: ./TGBot
    depends_on:
      - server
    
  
    volumes:
      - ./TGBot:/app  # монтируем в /app- ./TGBot:/app

    environment:
      - DATABASE_PATH=/app/tgbot.db
      - PYTHONUNBUFFERED=1

    restart: always

  db:
    container_name: 'database'
    image: postgres:15
    environment:
      - POSTGRES_DB=AduTime
      - POSTGRES_USER=waclaw
      - POSTGRES_PASSWORD=fvbyz123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U waclaw -d AduTime"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  server:
    driver: bridge
  check_updates:
    driver: bridge
  tgbot:
    driver: bridge

volumes:
  postgres_data:
  tgbot-data: