"""add table users and codes

Revision ID: 38eb0977de40
Revises: 999fffc7e89b
Create Date: 2026-02-28 22:14:54.300065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38eb0977de40'
down_revision: Union[str, Sequence[str], None] = '999fffc7e89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('userss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id')
    )
    op.drop_table('vstechincal_datas')
    op.add_column('vstechnical_archives', sa.Column('schedule', sa.Text(), nullable=False))
    op.drop_column('vstechnical_archives', 'data')
    op.alter_column('vstechnical_datas', 'date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vstechnical_datas', 'date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('vstechnical_archives', sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('vstechnical_archives', 'schedule')
    op.create_table('vstechincal_datas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('schedule', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vstechincal_datas_pkey'))
    )
    op.drop_table('userss')
    op.drop_table('codess')
    # ### end Alembic commands ###
