"""rename prepare_data to schedule

Revision ID: 8298f47342d7
Revises: 11256210e656
Create Date: 2025-11-20 18:24:09.734680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8298f47342d7'
down_revision: Union[str, Sequence[str], None] = '11256210e656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vstechincal_datas', sa.Column('schedule', sa.Text(), nullable=True))
    op.drop_column('vstechincal_datas', 'prepare_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vstechincal_datas', sa.Column('prepare_data', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('vstechincal_datas', 'schedule')
    # ### end Alembic commands ###
