"""add archive

Revision ID: 999fffc7e89b
Revises: 8298f47342d7
Create Date: 2026-01-11 17:24:00.619415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999fffc7e89b'
down_revision: Union[str, Sequence[str], None] = '8298f47342d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

<<<<<<< HEAD
def upgrade() -> None:
    # Сначала создаем таблицу, если её нет
    op.create_table('vstechnical_datas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('schedule', sa.Text(), nullable=False),
        sa.Column('date', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    print("СОЗДАЛАСЬ ТАБЛИЦА vstechnical_datas")
    
    # Если нужно создать другую таблицу
    op.create_table('vstechnical_archives',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('data', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    print("СОЗДАЛАСЬ ТАБЛИЦА vstechnical_archives")
=======

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vstechnical_archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Vstechnical_archive')
    op.alter_column('vstechincal_datas', 'schedule',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
>>>>>>> 72d1659d962418f5667d3a9f3ee0be9af88fd7b8


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD
    op.drop_table('vstechnical_archives')
    op.drop_table('vstechnical_datas')
=======
    op.alter_column('vstechincal_datas', 'schedule',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('Vstechnical_archive',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('Vstechnical_archive_pkey'))
    )
    op.drop_table('vstechnical_archives')
    # ### end Alembic commands ###
>>>>>>> 72d1659d962418f5667d3a9f3ee0be9af88fd7b8
