FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt .

RUN useradd -m -u 1000 -G root botuser && \
    chown -R botuser:root /app && \
    chmod -R 770 /app

# Добавить sudo без пароля
RUN apt-get update && apt-get install -y sudo && \
    echo "botuser ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER botuser

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
